_extends: .github
name-template: pipeline-stage-view-plugin-$RESOLVED_VERSION
tag-template: pipeline-stage-view-$RESOLVED_VERSION

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'dependencies'
  patch:
    labels:
      - 'bugfix'
      - 'patch'
  default: minor
